### ISSUE TITLE
Error on createExtension coc-pyright from coc-pyright/lib/index.js TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by BewareMyPower** [fannheyward/coc-pyright#1035]
**What's the output of `:CocCommand pyright.version`**

Error on "runCommand": Command: pyright.version not found

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Nothing.

**Additional Context**

```
2023-12-27T17:12:25.534 ERROR (pid:30518) [extensions] - Error on createExtension coc-pyright from /Users/xyz/.config/coc/extensions/node_modules/coc-pyright/lib/index.js TypeError: Cannot read properties of undefined (reading 'class')
    at Object.<anonymous> (/Users/xyz/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:113:677)
    at Module._compile (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:42447)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at r.require (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:42880)
    at mX (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:43402)
    at Object.activate (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:231:1206)
    at xX.activate (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:228:7366)
```

When I checked the source code of `~/.config/coc/extensions/node_modules/coc-pyright/lib/index.js`, it's really not human-readable. Is it expected? It seems that the `index.js` was generated from the TypeScript? (I'm not familiar with JS or TS)

```javascript
var Dj=[Zr.SemanticTokenTypes.class
```

It seems caused by `SemanticTokenTypes` not found?

**Comment by fannheyward** [comment]
You can get coc-pyright version from `:CocList extensions`.

**Comment by BewareMyPower** [comment]
It's the latest version

```
+ coc-pyright 1.1.342 ~/.config/coc/extensions/node_modules/coc-pyright
```

**Comment by fannheyward** [comment]
`:CocInfo` please.

**Comment by BewareMyPower** [comment]
## versions

vim version: VIM - Vi IMproved 9.0 9001598
node version: v20.4.0
coc.nvim version: 0.0.80-9fd90ad761
coc.nvim directory: /Users/xyz/.vim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim

2023-12-27T17:34:22.564 INFO (pid:31578) [services] - registered service "languageserver.rust"
2023-12-27T17:34:22.565 INFO (pid:31578) [services] - registered service "languageserver.ccls"
2023-12-27T17:34:22.565 INFO (pid:31578) [services] - registered service "languageserver.golang"
2023-12-27T17:34:22.681 ERROR (pid:31578) [extensions] - Error on createExtension coc-pyright from /Users/xyz/.config/coc/extensions/node_modules/coc-pyright/lib/index.js TypeError: Cannot read properties of undefined (reading 'class')
    at Object.<anonymous> (/Users/xyz/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:113:677)
    at Module._compile (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:42447)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at r.require (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:42880)
    at mX (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:227:43402)
    at Object.activate (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:231:1206)
    at xX.activate (/Users/xyz/.vim/plugged/coc.nvim/build/index.js:228:7366)
2023-12-27T17:34:22.684 INFO (pid:31578) [plugin] - coc.nvim 0.0.80-9fd90ad761 initialized with node: v20.4.0 after 148ms
2023-12-27T17:34:24.291 INFO (pid:31578) [attach] - receive notification: showInfo []

**Comment by BewareMyPower** [comment]
I updated the coc.nvim and it works now.
