### ISSUE TITLE
Language server fails to initialize

### ISSUE THREAD

**Issue by marcoaaguiar** [fannheyward/coc-pyright#134]
I'm trying to use coc-pyright but after installing and opening a python file I get the following:
`[coc.nvim] The "pyright" server crashed 5 times in the last 3 minutes. The server will not be restarted.`

The output is the following message repeated several times:
```bash[Info  - 1:14:21 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.5013 (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:1:561)
    at s (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:1:687)
    at Object.8863 (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-internal.js:1:801994)
    at s (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:1:687)
    at Object.5822 (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:1:46)
    at s (/home/marco/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:1:687)
```

CocInfo:
```bash
vim version: NVIM v0.5.0-823-g42ffa2d62
node version: v10.19.0
coc.nvim version: 0.0.79-bd91ae4254
coc.nvim directory: /home/marco/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

Am I missing something?

**Comment by fannheyward** [comment]
Pyright needs node v12+ to work https://github.com/microsoft/pyright/issues/769.

**Comment by pyrr** [comment]
Anyone getting this with v15.4.0

**Comment by marcoaaguiar** [comment]
@pyrr I saw a similar issue with coc-grammarly (https://github.com/gianarb/coc-grammarly/issues/8). 
He was also using node v15.4.0. Maybe this is a version issue. Could you check?

**Comment by mtoohey31** [comment]
Just want to weigh in on this, for what it's worth I'm also using coc-pyright with node v15.4.0 but I'm not experiencing this error on coc-pyright, only with coc-grammarly...
Sorry, I know that doesn't really clear things up, but that's the behaviour I'm experiencing.

**Comment by pyrr** [comment]
@marcoaaguiar Downgrading to the last lts version helped in my case.
