### ISSUE TITLE
Error on active extension coc-pyright

### ISSUE THREAD

**Issue by kiooss** [fannheyward/coc-pyright#205]
When open a python file after installed coc-pyright, the below error happened.

```
[coc.nvim]Error on active extension coc-pyright: Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "/Users/yang/workspace/python-web-api-demo", query: "", f
ragment: ""}
    at _validateUri (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:21241:19)
    at _URI.URI (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:21343:13)
    at new _URI (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:21545:47)
    at Function.URI.parse (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:21455:16)
    at Configurations.getFolderConfiguration (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:24122:34)
    at Configurations.getConfiguration (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:24045:84)
    at Workspace.getConfiguration (/Users/yang/.dotfiles/dotconfig/nvim/viml/plugins/coc.nvim/build/index.js:22570:36)
    at PythonSettings.initialize (/Users/yang/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:3298:52)
    at new PythonSettings (/Users/yang/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:3146:14)
    at Function.getInstance (/Users/yang/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:3153:30)
```

**Comment by fannheyward** [comment]
Can't reproduce, please upgrade your coc.nvim and coc-pyritht to latest release and try again.

**Comment by kiooss** [comment]
Thanks, seems to be version issue. Fixed by upgrade coc.nvim and coc-pyright to latest version.
