### ISSUE TITLE
Creating stub files

### ISSUE THREAD

**Issue by FelipeMarcelino** [fannheyward/coc-pyright#43]
Trying to create a stubs file for pandas:

:CocCommand pyright.createtypestub pandas

[coc.nvim] An error occurred when creating type stub for 'pandas': No typings path was specified
[coc.nvim] error: UnhandledRejection: Request workspace/executeCommand failed unexpectedly without providing any details.
Error: Request workspace/executeCommand failed unexpectedly without providing any details.
    at handleResponse (/home/felipemarcelino/.config/nvim/plugged/coc.nvim/build/index.js:15819:48)
    at processMessageQueue (/home/felipemarcelino/.config/nvim/plugged/coc.nvim/build/index.js:15646:1
7)
    at Immediate.<anonymous> (/home/felipemarcelino/.config/nvim/plugged/coc.nvim/build/index.js:15630
:13)
    at processImmediate (internal/timers.js:445:21)

**Comment by fannheyward** [comment]
Fixed, please `:CocUpdate coc-pyright` to upgrade.

**Comment by fannheyward** [comment]
Note that you need to create `pyrightconfig.json` config file in the root of your project. The stubs files will be create under `typings` folder.
