### ISSUE TITLE
Plugin install error.

### ISSUE THREAD

**Issue by walsripe** [fannheyward/coc-pyright#432]
**What's the output of `:CocCommand pyright.version`**
When I use CocInstall coc-pyright to install it. The log is as the below:

Install finished
- ✗ coc-pyright /usr/bin/yarn install exited with 2

**Comment by fannheyward** [comment]
Can't reproduce, properly it's a network error, `CocInstall` will fetch and install coc-pyright from npmjs.

**Comment by walsripe** [comment]
I don't think it is a network error because I can install other coc plugins by CocInstall as normal.

**Comment by tonybounty** [comment]
I've same error 
`2021-04-20T13:05:25.308 INFO (pid:45529) [attach] - receive notification: installExtensions [ 'coc-pyright' ]
2021-04-20T13:05:25.313 INFO (pid:45529) [model-installer] - Using npm from: /usr/bin/yarn
2021-04-20T13:05:25.314 INFO (pid:45529) [model-installer] - Get info from https://registry.npmjs.org/
2021-04-20T13:05:25.436 INFO (pid:45529) [model-installer] - Fetched info of coc-pyright {
  'dist.tarball': 'https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.129.tgz',
  'engines.coc': '^0.0.80',
  version: '1.1.129',
  name: 'coc-pyright'
}
2021-04-20T13:05:25.436 INFO (pid:45529) [model-installer] - Downloading from https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.129.tgz
2021-04-20T13:05:25.513 INFO (pid:45529) [model-installer] - Download progress 0.2%
2021-04-20T13:05:25.514 INFO (pid:45529) [model-installer] - Download progress 0.7%
2021-04-20T13:05:25.517 INFO (pid:45529) [model-installer] - Download progress 1.2%
2021-04-20T13:05:25.518 INFO (pid:45529) [model-installer] - Download progress 1.7%
2021-04-20T13:05:25.518 INFO (pid:45529) [model-installer] - Download progress 2.2%
2021-04-20T13:05:25.518 INFO (pid:45529) [model-installer] - Download progress 2.7%
2021-04-20T13:05:25.519 INFO (pid:45529) [model-installer] - Download progress 3.2%
2021-04-20T13:05:25.519 INFO (pid:45529) [model-installer] - Download progress 3.7%
2021-04-20T13:05:25.521 INFO (pid:45529) [model-installer] - Download progress 4.1%
2021-04-20T13:05:25.521 INFO (pid:45529) [model-installer] - Download progress 4.6%
2021-04-20T13:05:25.522 INFO (pid:45529) [model-installer] - Download progress 5.1%
2021-04-20T13:05:25.522 INFO (pid:45529) [model-installer] - Download progress 5.6%
2021-04-20T13:05:25.522 INFO (pid:45529) [model-installer] - Download progress 6.1%
2021-04-20T13:05:25.523 INFO (pid:45529) [model-installer] - Download progress 6.6%
2021-04-20T13:05:25.524 INFO (pid:45529) [model-installer] - Download progress 7.1%
2021-04-20T13:05:25.524 INFO (pid:45529) [model-installer] - Download progress 7.6%
2021-04-20T13:05:25.524 INFO (pid:45529) [model-installer] - Download progress 8.1%
2021-04-20T13:05:25.524 INFO (pid:45529) [model-installer] - Download progress 8.5%
2021-04-20T13:05:25.525 INFO (pid:45529) [model-installer] - Download progress 9.0%
2021-04-20T13:05:25.525 INFO (pid:45529) [model-installer] - Download progress 9.5%
2021-04-20T13:05:25.525 INFO (pid:45529) [model-installer] - Download progress 10.0%
2021-04-20T13:05:25.525 INFO (pid:45529) [model-installer] - Download progress 10.5%
2021-04-20T13:05:25.526 INFO (pid:45529) [model-installer] - Download progress 11.0%
2021-04-20T13:05:25.526 INFO (pid:45529) [model-installer] - Download progress 11.4%
2021-04-20T13:05:25.526 INFO (pid:45529) [model-installer] - Download progress 11.9%
2021-04-20T13:05:25.527 INFO (pid:45529) [model-installer] - Download progress 12.4%
2021-04-20T13:05:25.527 INFO (pid:45529) [model-installer] - Download progress 12.9%
2021-04-20T13:05:25.527 INFO (pid:45529) [model-installer] - Download progress 13.4%
2021-04-20T13:05:25.527 INFO (pid:45529) [model-installer] - Download progress 13.9%
2021-04-20T13:05:25.528 INFO (pid:45529) [model-installer] - Download progress 14.3%
2021-04-20T13:05:25.528 INFO (pid:45529) [model-installer] - Download progress 14.8%
2021-04-20T13:05:25.528 INFO (pid:45529) [model-installer] - Download progress 15.3%
2021-04-20T13:05:25.528 INFO (pid:45529) [model-installer] - Download progress 15.8%
2021-04-20T13:05:25.529 INFO (pid:45529) [model-installer] - Download progress 16.3%
2021-04-20T13:05:25.529 INFO (pid:45529) [model-installer] - Download progress 16.8%
2021-04-20T13:05:25.529 INFO (pid:45529) [model-installer] - Download progress 17.3%
2021-04-20T13:05:25.529 INFO (pid:45529) [model-installer] - Download progress 17.8%
2021-04-20T13:05:25.530 INFO (pid:45529) [model-installer] - Download progress 18.3%
2021-04-20T13:05:25.530 INFO (pid:45529) [model-installer] - Download progress 18.7%
2021-04-20T13:05:25.530 INFO (pid:45529) [model-installer] - Download progress 19.2%
2021-04-20T13:05:25.530 INFO (pid:45529) [model-installer] - Download progress 19.7%
2021-04-20T13:05:25.531 INFO (pid:45529) [model-installer] - Download progress 21.2%
2021-04-20T13:05:25.531 INFO (pid:45529) [model-installer] - Download progress 22.7%
2021-04-20T13:05:25.532 INFO (pid:45529) [model-installer] - Download progress 23.1%
2021-04-20T13:05:25.532 INFO (pid:45529) [model-installer] - Download progress 24.6%
2021-04-20T13:05:25.532 INFO (pid:45529) [model-installer] - Download progress 26.1%
2021-04-20T13:05:25.532 INFO (pid:45529) [model-installer] - Download progress 27.6%
2021-04-20T13:05:25.533 INFO (pid:45529) [model-installer] - Download progress 29.1%
2021-04-20T13:05:25.533 INFO (pid:45529) [model-installer] - Download progress 30.7%
2021-04-20T13:05:25.533 INFO (pid:45529) [model-installer] - Download progress 32.2%
2021-04-20T13:05:25.534 INFO (pid:45529) [model-installer] - Download progress 33.7%
2021-04-20T13:05:25.534 INFO (pid:45529) [model-installer] - Download progress 34.8%
2021-04-20T13:05:25.534 INFO (pid:45529) [model-installer] - Download progress 36.3%
2021-04-20T13:05:25.535 INFO (pid:45529) [model-installer] - Download progress 37.8%
2021-04-20T13:05:25.536 INFO (pid:45529) [model-installer] - Download progress 39.3%
2021-04-20T13:05:25.538 INFO (pid:45529) [model-installer] - Download progress 40.8%
2021-04-20T13:05:25.540 INFO (pid:45529) [model-installer] - Download progress 42.4%
2021-04-20T13:05:25.541 INFO (pid:45529) [model-installer] - Download progress 43.9%
2021-04-20T13:05:25.541 INFO (pid:45529) [model-installer] - Download progress 45.4%
2021-04-20T13:05:25.542 INFO (pid:45529) [model-installer] - Download progress 46.5%
2021-04-20T13:05:25.542 INFO (pid:45529) [model-installer] - Download progress 48.0%
2021-04-20T13:05:25.548 INFO (pid:45529) [model-installer] - Download progress 49.5%
2021-04-20T13:05:25.549 INFO (pid:45529) [model-installer] - Download progress 51.0%
2021-04-20T13:05:25.549 INFO (pid:45529) [model-installer] - Download progress 52.5%
2021-04-20T13:05:25.549 INFO (pid:45529) [model-installer] - Download progress 54.0%
2021-04-20T13:05:25.551 INFO (pid:45529) [model-installer] - Download progress 55.6%
2021-04-20T13:05:25.551 INFO (pid:45529) [model-installer] - Download progress 57.1%
2021-04-20T13:05:25.551 INFO (pid:45529) [model-installer] - Download progress 58.2%
2021-04-20T13:05:25.552 INFO (pid:45529) [model-installer] - Download progress 59.7%
2021-04-20T13:05:25.552 INFO (pid:45529) [model-installer] - Download progress 61.2%
2021-04-20T13:05:25.552 INFO (pid:45529) [model-installer] - Download progress 62.7%
2021-04-20T13:05:25.553 INFO (pid:45529) [model-installer] - Download progress 64.2%
2021-04-20T13:05:25.553 INFO (pid:45529) [model-installer] - Download progress 65.7%
2021-04-20T13:05:25.553 INFO (pid:45529) [model-installer] - Download progress 67.3%
2021-04-20T13:05:25.554 INFO (pid:45529) [model-installer] - Download progress 68.8%
2021-04-20T13:05:25.554 INFO (pid:45529) [model-installer] - Download progress 69.9%
2021-04-20T13:05:25.554 INFO (pid:45529) [model-installer] - Download progress 71.4%
2021-04-20T13:05:25.555 INFO (pid:45529) [model-installer] - Download progress 72.9%
2021-04-20T13:05:25.555 INFO (pid:45529) [model-installer] - Download progress 74.4%
2021-04-20T13:05:25.555 INFO (pid:45529) [model-installer] - Download progress 75.9%
2021-04-20T13:05:25.555 INFO (pid:45529) [model-installer] - Download progress 77.4%
2021-04-20T13:05:25.556 INFO (pid:45529) [model-installer] - Download progress 81.6%
2021-04-20T13:05:25.556 INFO (pid:45529) [model-installer] - Download progress 87.4%
2021-04-20T13:05:25.557 INFO (pid:45529) [model-installer] - Download progress 93.3%
2021-04-20T13:05:25.558 INFO (pid:45529) [model-installer] - Download progress 99.1%
2021-04-20T13:05:25.562 INFO (pid:45529) [model-installer] - Download progress 100.0%
2021-04-20T13:05:25.562 INFO (pid:45529) [model-download] - Download completed: https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.129.tgz
2021-04-20T13:05:25.563 INFO (pid:45529) [model-download] - Downloaded https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.129.tgz => /tmp/nvim5SYuWH/coc-pyright-CIYUtS
2021-04-20T13:05:25.664 INFO (pid:45529) [model-installer] - Extension download at /tmp/nvim5SYuWH/coc-pyright-CIYUtS
2021-04-20T13:05:25.665 INFO (pid:45529) [model-installer] - Installing dependencies by: /usr/bin/yarn install --ignore-scripts --no-lockfile --production --ignore-engines.
2021-04-20T13:05:25.789 INFO (pid:45529) [model-installer] - Usage: yarn [options]

yarn: error: no such option: --ignore-scripts

2021-04-20T13:05:25.789 ERROR (pid:45529) [extensions] - Error on install coc-pyright Error: /usr/bin/yarn install exited with 2
    at ChildProcess.<anonymous> (/home/tony/.local/share/nvim/plugged/coc.nvim/build/index.js:202:12805)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2021-04-20T13:05:26.117 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:05:48.488 INFO (pid:45529) [attach] - receive request: fillDiagnostics [ 7 ]
2021-04-20T13:05:48.797 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:05:50.310 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:08.497 INFO (pid:45529) [attach] - receive notification: openLog []
2021-04-20T13:06:08.827 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:10.982 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:13.247 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:13.840 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:14.670 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:15.384 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:17.697 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:27.786 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:28.610 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:29.529 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:33.837 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:06:40.083 INFO (pid:45529) [attach] - receive notification: highlight []
2021-04-20T13:07:33.115 INFO (pid:45529) [attach] - receive notification: highlight []
`
Yarn version 0.32+git
coc.nvim 0.0.80-4901b62416 initialized with node: v12.18.2 
NVIM v0.5.0-dev+1267-g7bf62ab02

**Comment by fannheyward** [comment]
@tonybounty what's your `/usr/bin/yarn --version`?

**Comment by tonybounty** [comment]
@fannheyward You're right, after apt install yarnpkg it's work
