### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by mnsgs** [fannheyward/coc-pyright#468]
Hi,

Installation (using `CocInstall coc-pyright`) fails with

```
2021-05-07T21:28:05.238 INFO (pid:541786) [model-download] - Download completed: https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.137.tgz
2021-05-07T21:28:05.239 INFO (pid:541786) [model-download] - Downloaded https://registry.npmjs.org/coc-pyright/-/coc-pyright-1.1.137.tgz => /tmp/nvimLkpqRn/coc-pyright-T1D3fF
2021-05-07T21:28:05.339 INFO (pid:541786) [model-installer] - Extension download at /tmp/nvimLkpqRn/coc-pyright-T1D3fF
2021-05-07T21:28:05.343 INFO (pid:541786) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2021-05-07T21:28:09.613 ERROR (pid:541786) [extensions] - Error on install coc-pyright Error: /usr/local/bin/npm install exited with 243
 at ChildProcess.<anonymous> (/home/martin/.local/share/nvim/plugged/coc.nvim/build/index.js:202:12805)
 at ChildProcess.emit (events.js:315:20)                                          
 at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)        

```
Other extensions work just fine - any ideas?

Thanks

**Comment by fannheyward** [comment]
Have no idea, try again.
