### ISSUE TITLE
hover provider not found for current buffer, your language server doesn't support it.

### ISSUE THREAD

**Issue by Kirenai** [fannheyward/coc-pyright#488]
When pressing ```<S + K>``` I get an error notification
```
## versions

vim version: VIM - Vi IMproved 8.2 8022871
node version: v14.12.0
coc.nvim version: 0.0.80-971c5f81b4
coc.nvim directory: C:\Users\Kire\.vim\plugged\coc.nvim
term: undefined
platform: win32

## Log of coc.nvim

2021-05-20T00:14:45.925 INFO (pid:5800) [services] - registered service "pyright"
2021-05-20T00:14:45.929 INFO (pid:5800) [services] - Pyright Server state change: stopped => starting
2021-05-20T00:14:45.953 INFO (pid:5800) [plugin] - coc.nvim 0.0.80-971c5f81b4 initialized with node: v14.12.0 after 289ms
2021-05-20T00:14:46.002 INFO (pid:5800) [language-client-index] - pyright started with 2356
2021-05-20T00:14:55.404 INFO (pid:5800) [attach] - receive notification: doHover []
2021-05-20T00:14:55.408 ERROR (pid:5800) [attach] - Notification error: doHover [] Error: hover provider not found for current buffer, your language server doesn't support it.
    at MP.checkProvier (C:\Users\Kire\.vim\plugged\coc.nvim\build\index.js:246:1043)
    at MP.onHover (C:\Users\Kire\.vim\plugged\coc.nvim\build\index.js:246:2725)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async qP.cocAction (C:\Users\Kire\.vim\plugged\coc.nvim\build\index.js:247:11564)
    at async nM.<anonymous> (C:\Users\Kire\.vim\plugged\coc.nvim\build\index.js:129:12652)
2021-05-20T00:14:59.404 INFO (pid:5800) [attach] - receive notification: highlight []
2021-05-20T00:15:03.643 INFO (pid:5800) [attach] - receive notification: showInfo []
```

I do not know what is happening, with tsx files if it works, with coc-tsserver

$HOME\\_vimrc

```vim
syntax on
set nolist
set number
set mouse=a
set clipboard=unnamed
set showcmd
set ruler
set encoding=utf8
set showmatch
set sw=4
set relativenumber
let mapleader = ","
set laststatus=2
set backspace=2
set guioptions-=T
set guioptions-=L
set belloff=all
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab 

" Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8

" Python .dll
set pythonthreehome=$HOME\AppData\Local\Programs\Python\Python39
set pythonthreedll=$HOME\AppData\Local\Programs\Python\Python39\python39.dll

imap ii <Esc>

"Mapping to reload config
nmap <leader>so :source $HOME\_vimrc<CR>
nmap <leader>w :w <CR>
nmap <leader>q :q <CR>

"Mapping to error
" Remap keys for applying codeAction to the current line.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition) 
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

" Tab navigation like Firefox.
nnoremap <C-S-tab> :bprevious<CR>
nnoremap <C-tab>   :bnext<CR>

" Commands
command! Config execute ":e $HOME\\_vimrc"
command! Source execute ":source $HOME\\_vimrc"

" Ident config
"autocmd! BufNewFile,BufReadPre,FileReadPre *.py so $HOME\vimfiles\ftplugin\python.vim

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
"
"
call plug#begin('~/.vim/plugged')
  " Temas
  Plug 'morhetz/gruvbox'
  "IDE
  Plug 'easymotion/vim-easymotion'
  "Nerdtree
  Plug 'preservim/nerdtree'
  "vim-tmux-navigator ctrl + h | j | k | l to jump
  Plug 'christoomey/vim-tmux-navigator'
  "vim-airline & themes
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  "JS & TS suppport
  Plug 'pangloss/vim-javascript'    " JavaScript support
  Plug 'leafgarland/typescript-vim' " TypeScript syntax
  Plug 'maxmellon/vim-jsx-pretty'   " JS and JSX syntax
  Plug 'neoclide/coc.nvim' , { 'branch' : 'release' }
call plug#end()

" NERDTree command
nmap <Leader>nt :NERDTreeFind<CR>
" Command to find to characters
nmap <Leader>s <Plug>(easymotion-s2)
colorscheme gruvbox

"COC.VIM variables
let g:coc_global_extensions = [ 'coc-tsserver', 'coc-json' ]
"GRUVBOX variables
let g:gruvbox_contrast_dark = "hard"
"NERDTree variables
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.git$', '\.idea$', '\.vscode$', '\.history$']
"airline variables
let g:airline_theme = 'onedark'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_powerline_fonts = 1
let g:airline_left_sep = ''
let g:airline_right_sep = ''
```

**Comment by fannheyward** [comment]
Can't reproduce, are you opening on a Python file?

**Comment by Kirenai** [comment]
yes, I have a Python file open

attached image

![image](https://user-images.githubusercontent.com/66179578/119030772-f18d2680-b96f-11eb-9e12-06aa5ca1699e.png)

trying with the print function and it doesn't work, when I first installed the coc-pyright, it did work, but when I closed and opened gVim it stopped working

**Comment by yaegassy** [comment]
@Kirenai What directory is the "project root" for that program of yours?

In some cases, hover may not work if the pyright language server does not detect the root of the project correctly.

If I navigate to the "project root" with `:cd` and then run `:CocRestart`, does the hover work?

**Example**:

```
:cd /path/to/projectroot
:CocRestart
```

Alternatively, placing `pyrightconfig.json` in the project root may solve the problem.

**Comment by Kirenai** [comment]
@yaegassy Thank you so much

The root of my project is ~\cisco and with the example you put to help me it worked, the hover is working.

I didn't have to create the ```pyrightconfig.json``` file.

Attached image of the hover working:

![image](https://user-images.githubusercontent.com/66179578/119083355-722a4200-b9c5-11eb-9d70-ce3e93c7d0cb.png)

Thank you very much for your time. :)
