### ISSUE TITLE
Getting error Unknown function: coc#util#echo_line

### ISSUE THREAD

**Issue by farzadmf** [fannheyward/coc-pyright#600]
When saving a Python file, I get the following error:
```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
Error
    at ON.request (/home/farzad/.vim/plugged/coc.nvim/build/index.js:30:34613)
    at ON.call (/home/farzad/.vim/plugged/coc.nvim/build/index.js:33:3671)
    at Timeout._onTimeout (/home/farzad/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:21911:33)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.163 with Pyright 1.1.163
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /tmp/algo/disjoint
Using python from /tmp/algo/disjoint/.direnv/python-3.9.6/bin/python

[Info  - 11:07:38 a.m.] Pyright language server 1.1.163 starting
[Info  - 11:07:38 a.m.] Server root directory: /home/farzad/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 11:07:38 a.m.] No configuration file found.
[Info  - 11:07:38 a.m.] No pyproject.toml file found.
[Info  - 11:07:38 a.m.] Setting pythonPath for service "disjoint": "/tmp/algo/disjoint/.direnv/python-3.9.6/bin/python"
[Warn  - 11:07:38 a.m.] stubPath /tmp/algo/disjoint/typings is not a valid directory.
[Info  - 11:07:38 a.m.] Assuming Python version 3.9
[Info  - 11:07:38 a.m.] Assuming Python platform Linux
[Warn  - 11:07:38 a.m.] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 11:07:38 a.m.] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 11:07:38 a.m.] Searching for source files
[Info  - 11:07:38 a.m.] Auto-excluding /tmp/algo/disjoint/.direnv/python-3.9.6
[Info  - 11:07:38 a.m.] Found 1 source file
```

**Comment by MoronVV** [comment]
I got same error not on saving, but on `:call CocAction('format')` command

**Comment by farzadmf** [comment]
I think I get it upon save because I have format-on-save enabled

**Comment by badicsalex** [comment]
https://github.com/fannheyward/coc-pyright/blob/master/src/formatters/baseFormatter.ts#L135

The `coc#util#echo_line` function no longer exists in coc: neoclide/coc.nvim@00ed6677383

**Comment by fannheyward** [comment]
Fixed in v1.1.164, please `:CocUpdate`.

**Comment by badicsalex** [comment]
That was super quick, thanks!

**Comment by farzadmf** [comment]
Amazing! thank you @fannheyward

**Comment by dammmn** [comment]
Has this been reintroduced again  ? 

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line                                                              
Error                                                                                                                                                                          
    at wF.request (/home/dciprus/.config/nvim/plugins/coc.nvim/build/index.js:30:34430)                                                                                        
    at wF.call (/home/dciprus/.config/nvim/plugins/coc.nvim/build/index.js:33:3671)                                                                                            
    at Timeout._onTimeout (/home/dciprus/.config/coc/extensions/node_modules/coc-python/lib/index.js:123358:39)                                                                
    at listOnTimeout (internal/timers.js:554:17)                                                                                                                               
    at processTimers (internal/timers.js:497:7)  
```
```
[coc.nvim] coc-pyright 1.1.166 with Pyright 1.1.166
```

```
Workspace: /mnt/passport/data/Documents/Customers/****/code/****_nso
Using python from /usr/bin/python

[Info  - 10:24:07 AM] Pyright language server 1.1.166 starting
[Info  - 10:24:07 AM] Server root directory: /home/dciprus/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
```

**Comment by fannheyward** [comment]
@dammmn you're using coc-python, not coc-pyright.

**Comment by dammmn** [comment]
> @dammmn you're using coc-python, not coc-pyright.

Oh .. my bad :-/ ... I introduced few more plugins  recently and looks like I mistyped something somewhere which led into this. Apologies ! ... and thank you for great work you've done !
