### ISSUE TITLE
Go to references get errors

### ISSUE THREAD

**Issue by fred214** [fannheyward/coc-pyright#673]
NVIM v0.5.0
python 3.9.9
jedi 0.18.1

coc-setting.json
```
{
     "python.pythonPath": "python3"
}
```
`gd` go to definition works well, but when `gr` go to references, it report error message:
```
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "/Users/I500257/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py", line 672, in watch
    response = self._process_request(rq)
  File "/Users/I500257/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py", line 644, in _process_request
    return self._serialize_usages(
  File "/Users/I500257/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py", line 524, in _serialize_usages
    return json.dumps({"id": identifier, "results": _usages})
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**Comment by fannheyward** [comment]
> /Users/I500257/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py

You're using coc-python, not coc-pyright.

**Comment by fannheyward** [comment]
You're using coc-python, not coc-pyright.
