### ISSUE TITLE
"&nbsp" instead of whitespaces in docstring popups when opening parenthesis

### ISSUE THREAD

**Issue by Andrew15-5** [fannheyward/coc-pyright#701]
Hi, I was wondering if this problem is in fact a bug, or I just need something to put in config file. I've seen theses "&nbsp" quite a lot for the past year or so of using coc-pyright extension. By the way, I'm currently using Neovim v0.7.0-dev, but this issue was present on v0.6 and v0.5.

Here's the description of the issue itself:
When 'K' was pressed (when carriage is) on function name or choosing it from auto-completion list, then its description in popup windows shows correctly:
![on_function](https://user-images.githubusercontent.com/37143421/152221509-03c22dac-7922-4271-ba94-6deb9cbe0bb3.png)
![image](https://user-images.githubusercontent.com/37143421/152221960-cc099129-0b4f-4476-8925-da2a0d098d81.png)

But when opening parenthesis of the function, then description shows with a lot of "&nbsp" instead of whitespaces:
![in_parentheses](https://user-images.githubusercontent.com/37143421/152221458-4c46c84f-c6d6-492d-ba2d-32c17d461adb.png)

**What's the output of `:CocCommand pyright.version`**
```bash
[coc.nvim] coc-pyright 1.1.215 with Pyright 1.1.217
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```bash
Workspace: /home/user
Using python from /usr/bin/python3

[Warn  - 9:11:47 PM] disableCompletion in the client options is deprecated. use disabledFeatures instead.
Error
    at new dD (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:216:39287)
    at new Yh (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:222:27963)
    at Object.activate (/home/user/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
    at /home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:236:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:236:1369)
    at A5.activate (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:233:7436)
    at /home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:235:283
    at new Promise (<anonymous>)
    at s (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:235:45)
[Warn  - 9:11:47 PM] disableDiagnostics in the client options is deprecated. use disabledFeatures instead.
Error
    at new dD (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:216:39287)
    at new Yh (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:222:27963)
    at Object.activate (/home/user/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
    at /home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:236:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:236:1369)
    at A5.activate (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:233:7436)
    at /home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:235:283
    at new Promise (<anonymous>)
    at s (/home/user/.config/nvim/autoload/plugged/coc.nvim/build/index.js:235:45)
```

**Comment by yaegassy** [comment]
@Andrew15-5 If you are concerned about `&nbsp;`, try setting `"coc.preferences.enableMarkdown": false` in "coc-settings.json".

**e.g.**:

```jsonc
}
  "coc.preferences.enableMarkdown": false,
}
```

**Comment by Andrew15-5** [comment]
Yes! That's it, thank you.
