### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by dagadbm** [fannheyward/coc-pyright#73]
When I try to use coc-pyright (with our without coc-python) I get the following eerror:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack://pyright-server/external_%22worker_threads%22?:1:18)
    at Object.worker_threads (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3803:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
    at eval (webpack://pyright-server/./src/server.ts?:19:26)
    at Object../src/server.ts (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:2295:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
[Info  - 11:59:00 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack://pyright-server/external_%22worker_threads%22?:1:18)
    at Object.worker_threads (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3803:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
    at eval (webpack://pyright-server/./src/server.ts?:19:26)
    at Object../src/server.ts (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:2295:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
[Info  - 11:59:00 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack://pyright-server/external_%22worker_threads%22?:1:18)
    at Object.worker_threads (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3803:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
    at eval (webpack://pyright-server/./src/server.ts?:19:26)
    at Object../src/server.ts (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:2295:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
[Info  - 11:59:00 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack://pyright-server/external_%22worker_threads%22?:1:18)
    at Object.worker_threads (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3803:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
    at eval (webpack://pyright-server/./src/server.ts?:19:26)
    at Object../src/server.ts (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:2295:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
[Info  - 11:59:00 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at eval (webpack://pyright-server/external_%22worker_threads%22?:1:18)
    at Object.worker_threads (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3803:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
    at eval (webpack://pyright-server/./src/server.ts?:19:26)
    at Object../src/server.ts (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:2295:1)
    at __webpack_require__ (/Users/david.maia/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/pyright-langserver.js:3826:42)
[Error  - 11:59:00 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by dagadbm** [comment]
I need to use a version higher than node 10. Node 14 works.
