### ISSUE TITLE
ReferenceError: CompletionItemKind is not defined

### ISSUE THREAD

**Issue by mattbonnell** [fannheyward/coc-pyright#819]
**What's the output of `:CocCommand pyright.version`**
```
[coc.nvim] coc-pyright 1.1.271 with Pyright 1.1.271
```

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /Users/[redacted]/[redacted]/[redacted]
Using python from /Users/[redacted]/.pyenv/versions/3.7.13/envs/[redacted]/bin/python

[Info  - 8:38:11 AM] Pyright language server 1.1.271 starting
[Info  - 8:38:11 AM] Server root directory: /Users/[redacted]/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 8:38:11 AM] Starting service instance "[redacted]"
[Info  - 8:38:11 AM] No configuration file found.
[Info  - 8:38:11 AM] No pyproject.toml file found.
[Info  - 8:38:11 AM] Setting pythonPath for service "[redacted]": "/Users/[redacted]/.pyenv/versions/3.7.13/envs/[redacted]/bin/python"
[Warn  - 8:38:11 AM] stubPath /Users/[redacted]/[redacted]/[redacted]/typings is not a valid directory.
[Info  - 8:38:11 AM] Assuming Python version 3.7
[Info  - 8:38:11 AM] Assuming Python platform Darwin
[Info  - 8:38:12 AM] Searching for source files
[Error  - 8:38:22 AM] Enumeration of workspace source files is taking longer than 10 seconds.
This may be because:
* You have opened your home directory or entire hard drive as a workspace
* Your workspace contains a very large number of directories and files
* Your workspace contains a symlink to a directory with many files
* Your workspace is remote, and file enumeration is slow
To reduce this time, open a workspace directory with fewer files or add a pyrightconfig.json configuration file with an "exclude" section to exclude subdirectories from your workspace. For more details, refer to https://github.com/microsoft/pyright/blob/main/docs/configuration.md.
[Info  - 8:38:25 AM] Found 79473 source files
```

The following error is popping as I type the names of members I'm importing from a module (eg I start to type `from typing import Dict`):

```
2022-09-15T08:38:30.911 ERROR (pid:96426) [node-client] - ReferenceError: CompletionItemKind is not defined Error
    at HM.echoError (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:35:1869)
    at AD.completeSource (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:33467)
    at async Promise.all (index 0)
    at async AD.completeSources (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:32390)
    at async AD.doComplete (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:31939)
    at async Ste.startCompletion (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:47046)
    at async Ste.triggerCompletion (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:49480)
    at async Ste.onTextChangedI (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:278:48395)
2022-09-15T08:38:30.911 ERROR (pid:96426) [completion-complete] - Complete error: python-import ReferenceError: CompletionItemKind is not defined
    at ImportCompletionProvider.provideCompletionItems (/Users/[redacted]/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:91699:63)
    at async pD.doComplete (/Users/[redacted]/.vim/plugged/coc.nvim/build/index.js:274:11250)
```

**Comment by fannheyward** [comment]
Reproduced.
