### ISSUE TITLE
[coc.nvim] uncaughtException Error: write EPIPE with ruff

### ISSUE THREAD

**Issue by owocado** [fannheyward/coc-pyright#885]
**What's the output of `:CocCommand pyright.version`**
coc-pyright 1.1.293 with Pyright 1.1.293

**What's the output of `:CocCommand workspace.showOutput Pyright`**
![image](https://user-images.githubusercontent.com/24418520/218022556-55e89542-73e0-4eb7-b938-39e1f91e69e9.png)

--------------------------
Greetings,

I recently heard about ruff and its amazing features for linting so I decided to try it out with coc-pyright.
I installed ruff through pypi and current version on my machine is 0.0.244
This is my coc-settings.json:
```json
{
    "pyright.enable": true,
    "python.analysis.autoImportCompletions": true,
    "python.analysis.diagnosticSeverityOverrides": {
        "reportCallInDefaultInitializer": "information",
        "reportDuplicateImport": "information",
        "reportGeneralTypeIssues": "information",
        "reportMissingParameterType": "information",
        "reportMissingImports": "information",
        "reportMissingTypeStubs": "information",
        "reportOptionalMemberAccess": "information",
        "reportOptionalOperand": "information",
        "reportPropertyTypeMismatch": "information",
        "reportTypeCommentUsage": "information",
        "reportUninitializedInstanceVariable": "none",
        "reportUnusedImport": "information",
        "reportUnusedVariable": "information",
        "reportUnnecessaryCast": "information",
        "reportUnnecessaryComparison": "information",
        "reportUnnecessaryIsInstance": "information",
        "reportUnnecessaryTypeIgnoreComment": "information"
    },
    "python.pythonPath": "/opt/P311/bin/python",
    "python.venvPath": "/opt/P311",
    "python.formatting.provider": "black",
    "python.formatting.blackPath": "/opt/P311/bin/black",
    "python.linting.enabled": true,
    "python.linting.ruffEnabled": true,
    "python.linting.ruffPath": "/opt/P311/bin/ruff",
    "python.sortImports.path": "/opt/P311/bin/isort",
    "pyright.completion.snippetSupport": true,
    "pyright.disableProgressNotifications": true,
    "signature.triggerSignatureWait": 5000,
    "javascript.suggestionActions.enabled": false
}
```

Though whenever I open any python file, I get the exact message I mentioned in issue title highlighted in red in bottom status bar in vim. This is my recent output of `:CocOpenLog` file:
```bash
2023-02-10T07:58:37.700 INFO (pid:324049) [plugin] - coc.nvim initialized with node: v18.14.0 after 571
2023-02-10T07:58:37.702 INFO (pid:324049) [services] - LanguageClient Pyright Server state change: stopped => starting
2023-02-10T07:58:37.718 INFO (pid:324049) [language-client-index] - Language server "pyright" started with 324073
2023-02-10T07:58:37.948 INFO (pid:324049) [services] - LanguageClient Pyright Server state change: starting => running
2023-02-10T07:58:37.956 INFO (pid:324049) [services] - service pyright started
2023-02-10T07:58:38.933 ERROR (pid:324049) [server] - uncaughtException Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Ruff.stdinRun (/home/eon/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:96884:81)
    at Ruff.run (/home/eon/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:96900:35)
    at Ruff.runLinter (/home/eon/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:97381:17)
2023-02-10T07:58:38.933 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:41.570 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:43.381 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:45.156 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:45.491 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:45.986 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:53.986 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:54.739 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:55.137 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:55.963 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:56.434 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:56.958 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:57.430 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:57.837 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:58.846 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:58:59.377 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:00.638 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:01.159 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:03.731 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:07.260 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:07.991 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:09.026 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:10.012 INFO (pid:324049) [attach] - receive notification: highlight []
2023-02-10T07:59:11.098 INFO (pid:324049) [attach] - receive notification: highlight []
```

I was a bit unsure and hesitant where to open this issue, whether in coc.nvim repo, ruff repo or here since I couldn't figure out if ruff/coc or coc-pyright is cause of this but I eventually decided to ask here. Apologies if this is not relevant to coc-pyright, in that case please close the issue and guide me where should I go. Thank you for reading. ^^

**Comment by fannheyward** [comment]
Thank you for your report, will debug this later.

**Comment by fannheyward** [comment]
In my tests, I can't reproduce this. What's the output of `:CocCommand workspace.showOutput coc-pyright-linting`?

**Comment by fannheyward** [comment]
> uncaughtException Error: write EPIPE

coc-pyright runs `ruff` process and send document text to the process as stdin. This error looks like the process was ended before text write.
